FROM golang:1.16-alpine as builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go build -ldflags='-w -s' -o server

FROM scratch

WORKDIR /app

COPY --from=builder /app/server .

USER 1000

EXPOSE 8080

CMD ["./server"]
