FROM node:16-alpine as build-stage

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM alpine:3.16

RUN apk add --no-cache npm && \
    npm install -g serve && \
    adduser -S appuser && \
    rm -rf /var/cache/apk/* /tmp/* /var/tmp/*

WORKDIR /usr/src/app

COPY --from=build-stage /usr/src/app/build ./build

ENV REACT_APP_BACKEND_URL=http://localhost:8080
ENV PORT=5000

EXPOSE 5000

USER appuser

# Command to serve the built React application
CMD ["serve", "-s", "build", "-l", "5000"]
