version: '3.8'

services:
    example-backend:
      build:
        context: ./example-backend
      environment:
        REDIS_HOST: redis
        POSTGRES_HOST: db
      depends_on:
        - redis
        - db

    example-frontend:
      build: 
        context: ./example-frontend
      depends_on:
        - example-backend

    redis:
      image: redis:alpine
      restart: unless-stopped

    db:
      image: postgres:13.2-alpine
      restart: unless-stopped
      environment:
        POSTGRES_PASSWORD: postgres
      volumes:
        - ./database:/var/lib/postgresql/data
      container_name: db

    nginx:
      image: nginx:alpine
      ports:
        - "80:80"
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - example-frontend
        - example-backend

volumes:
  database: