FROM node:16-alpine

WORKDIR /usr/src/app

EXPOSE 5000

COPY . .

ENV REACT_APP_BACKEND_URL=http://localhost:8080

RUN npm install -g serve && \
    npm install && \
    npm run build && \
    adduser -S appuser && \
    rm -rf ./node_modules ./src

USER appuser

CMD ["serve", "-s", "-l", "5000", "build"]
