version: '3.8'

services:
    example-backend:
        build:
            context: ./example-backend
        ports:
            - "8080:8080"

    example-frontend:
        build:
            context: ./example-frontend
        ports:
            - "5000:5000"
        depends_on:
            - example-backend
