version: '3.8'

services:
    example-backend:
      build:
        context: ./example-backend
      ports:
        - "8080:8080"
      environment:
        REDIS_HOST: redis
        POSTGRES_HOST: db
      depends_on:
        - redis
        - db

    example-frontend:
      build: 
        context: ./example-frontend
      ports:
        - "5000:5000"
      depends_on:
        - example-backend

    redis:
      image: redis:alpine
      restart: unless-stopped
      ports:
        - "6379:6379"

    db:
      image: postgres:13.2-alpine
      restart: unless-stopped
      environment:
        POSTGRES_PASSWORD: postgres
      ports:
        - "5432:5432"
      volumes:
        - ./database:/var/lib/postgresql/data
      container_name: db

volumes:
  database: